# loki-stack-values.yaml
loki:
  image:
    tag: '2.9.3'
  enabled: true
  persistence:
    enabled: false
  service:
    type: ClusterIP
  serviceAccount:
    create: false
    name: loki-s3-sa
  config:
    schema_config:
      configs:
        - from: 2025-06-13
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: s3
      aws:
        s3: live-loki-s3
        region: ap-northeast-2
    chunk_store_config:
      max_look_back_period: 168h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123 # Grafana 비밀번호
  service:
    type: ClusterIP
    port: 3000
  persistence:
    enabled: false
  datasources:
    enabled: true
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki-stack:3100
          access: proxy
          isDefault: true
promtail:
  enabled: true