name: app-build-and-push

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.git'
      - 'assets'
      - 'cd'
      - 'infra'
      - 'docs'
      - 'README.md'
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: main-app # cd/kustomize/base/example_app.yaml 내용과 일치시키는 것을 권장
            context: ./src # 실제 빌드 경로에 맞게 수정 필요
            dockerfile: ./src/Dockerfile # 실제 빌드 경로에 맞게 수정 필요

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.dockerfile }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ github.sha }}

    - name: Push to cd
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/cdkkim/de-mlops.git
        cd de-mlops/cd/kustomize/overlays/dev
        yq eval '.images[].newTag = "${{ github.sha }}"' -i kustomization.yaml
        git add .
        git commit -m "Update from GitHub Actions" || echo "No changes to commit"
        git push
